language: shell
sudo: required
services:
  - docker
script:
  - docker build -t ncdevop/nginxhello .
after_success:
  - docker run -d -p80:80 ncdevop/nginxhello:latest
after_script:
   - |
    output='zzz'
    if [[ $(curl -v --silent http://localhost:80 2>&1 | egrep "$output") ]]; then
      echo "The desired output string ($output) is present. Continuing"
      docker tag ncdevop/nginxhello $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      docker tag ncdevop/nginxhello $DOCKER_USER/nginxhello:latest
      docker login -u $DOCKER_USER -p $DOCKER_PASSWD && docker push $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      exit 0
    else
      echo 'curl test failed so exiting'
      exit 1
    fi
