language: shell
os: linux
dist: xenial

install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config

services:
  - docker
script:
  - docker pull ncdevop/nginxhello:latest
  - docker images
after_success:
  - docker run -d -p 80:80 ncdevop/nginxhello:latest
after_script:
  - |
    output='Hello World!'
    if [[ $(curl -v --silent http://localhost:80 2>&1 | egrep "$output") ]]; then
      docker tag $DOCKER_USER/nginxhello $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      docker login -u $DOCKER_USER -p $DOCKER_PASSWD && docker push $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      kubectl create deployment $DOCKER_USER-nginxhello-$TRAVIS_BUILD_NUMBER --image=$DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      kubectl expose deployment $DOCKER_USER-nginxhello-$TRAVIS_BUILD_NUMBER --type=LoadBalancer --port=80 --target-port=80
    else
      echo 'Curl test for proper response failed so exiting'
      exit 1
    fi
