language: shell
sudo: required
services:
  - docker
script:
  - docker build -t ncdevop/nginxhello .
after_success:
  - docker run -d -p80:80 ncdevop/nginxhello:latest

  - if [ curl -v --silent http://localhost:80 2>&1 | egrep 'Hello World!' == "true" ]; then
      echo "curl test success"
      docker tag ncdevop/nginxhello $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
      docker tag ncdevop/nginxhello $DOCKER_USER/nginxhello:latest
      docker login -u $DOCKER_USER -p $DOCKER_PASSWD && docker push $DOCKER_USER/nginxhello:$TRAVIS_BUILD_NUMBER
    else
      echo "curl test failed"
    fi
